import localFont from "next/font/local";
import Header from "@/components/header";

import "./globals.css";

const inter = localFont({
  src: "./fonts/inter.ttf",
  variable: "--font-inter",
  weight: "300 500 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
